### ISSUE TITLE
Hang while processing 2K by 16K map

### ISSUE THREAD

**Issue by kvark** [PsichiX/density-mesh#5]
Trying out the map generator with the following code:
```rust
                let map = DensityMap::new(extent.width as usize, extent.height as usize, 1, raw_data).unwrap();
                let settings = GenerateDensityMeshSettings {
                    points_separation: 16.0.into(),
                    keep_invisible_triangles: false,
                    ..Default::default()
                };
                // create live density mesh.
                let mut live = LiveDensityMesh::new(map, settings);
                // perform initial processing.
                live.process_wait().unwrap();
```
The map is 2K by 16K. I waited for more than an hour for a release build, it hasn't finished.
Here is the test file - 
![vangers-density](https://user-images.githubusercontent.com/107301/96209689-349c9c80-0f3e-11eb-8467-ea3cd8fd23ea.jpg)
(I wasn't able to upload the lossless PNG version, since it's above 10Megs)

**Comment by PsichiX** [comment]
hi! i've found many more problems with live density mesh for big maps and right now i'm currently rewriting it to work on snall changes, should be ready on monday :D

**Comment by kvark** [comment]
Great, thank you! In the meantime, is there a way to generate the mesh statically? I've only been able to find https://docs.rs/density-mesh-image/1.3.0/density_mesh_image/fn.generate_densitymap_from_image.html , which depends on Image crate.

**Comment by PsichiX** [comment]
during last week work on new live mesh generation i was fighting with spade's iterative adding/removing of vertices that has a nasty internal infinite loop bug on vertices remove. trying to fix it was a nightmare and i failed to fix it properly without introducing new bugs, which means i have to make a dedicated triangulation from scratch that will work with live vertices removal.
about static mesh generation, i'm gonna post an example after work today, stay tuned! :D

**Comment by PsichiX** [comment]
covid situation and deadlines at work made me able to work a couple hours on weekends.
long story short: i was about to say that dynamic points removal in spade's delaunay was impossible to not fall into internal infinite loops which makes this problem impossible to solve atm, then i changed spade back into triangulation crate and found out that my entire region change points selection algorithm after refactoring, was more or less a bunch of crap - so there is a light in the tunnel! working on it rn :D

**Comment by PsichiX** [comment]
ok, after fixing this particular problem it showed me that there are more.
sadly, i have to say this: for now, at this moment, it is not possible to make **reliable** live terrain updates other than rebuilding the whole mesh from the whole density map on each change. i'm going to prepare new update to do that to make sure it always gives reliable output, and try to optimize as much as i can based on that. i could jump into the live mesh generation again in next month :<

**Comment by kvark** [comment]
I'll be happy to test it once ready. No rush from my side, and thank you for all the hard work!

**Comment by PsichiX** [comment]
there is new version, example is listed in README, as well as playground app is in the `density-mesh-playground` project.
please note, that atm with your map it is reeeeeeeaaaaaally slow, so i'm gonna work on optimizing this with your map you've provided in a month or so :)

**Comment by kvark** [comment]
Thank you! Note that I don't need that published on crates, necessarily. I'm fine with a github dependency, so that we can iterate faster.

**Comment by kvark** [comment]
Ok, I tried it, and now I see why you had so many "e" and "a" in that "really" word. It's not only non-realtime, it's more of a supercomputer task now. Is it remotely feasible to get this close to realtime somehow? Maybe trading performance for quality or something?

**Comment by kvark** [comment]
Basically, this comes down to using proper settings, but I don't know what they mean. So putting proper documentation in place for them would be great - #4!
